function generateContent4(){
    //Question blank object
    var newQuestion = new QuestionObj();
    
    newQuestion.isDeployed = true;
    newQuestion.anchor = 'Operations with Real Numbers and Expressions';
    newQuestion.content = 'Use estimation to solve problems';

    //Store and items will be generated by random
    var store, item1, item2;
    
    //random number 0-4
    //5 different store/items
    var temp1 = Math.floor(Math.random() * 5);
    if (temp1 == 0)
    {
        store = "hardware store";
        item1 = "totes of nails";
        item2 = "totes of screws";
    }
    else if (temp1 == 1)
    {
        store = "pet shop";
        item1 = "cats";
        item2 = "dogs";
    }
    else if (temp1 == 2)
    {
        store = "electronic store";
        item1 = "speakers";
        item2 = "tvs";
    }
    else if (temp1 == 3)
    {
        store = "sports shop";
        item1 = "hockey sticks";
        item2 = "baseball bats";
    }
    else
    {
        store = "furniture store";
        item1 = "chairs";
        item2 = "tables";
    }
    
    var item1Cost, item1CostEstimate, item1Sales, item1SalesEstimate;
    var item2Cost, item2CostEstimate, item2Sales, item2SalesEstimate;
    //Loop to make sure correct answer is divisible by 10000
    do
    {
        //Random cost of $50, $100, $150, $200, or $250
        item1CostEstimate = Math.floor((Math.random() * 5) + 1) * 50;
        
        //Random cost estimate of $300, $400, $500, or $600 
        item2CostEstimate = Math.floor((Math.random() * 4) + 3) * 100;
        
        //random number -10 to 10, not including 0
        temp1 = Math.floor((Math.random() * 20) - 10);
        if (temp1 == 0) temp1 = 10; 
        item1Cost = item1CostEstimate + temp1;
        
        //random number -20 to 20, not including 0
        temp1 = Math.floor((Math.random() * 40) - 20);
        if (temp1 == 0) temp1 = 20; 
        item2Cost = item2CostEstimate + temp1;
        
        //random number, 100-800, every 100
        item1SalesEstimate = Math.floor((Math.random() * 8) + 1) * 100;

        //random number, 100-800, every 100
        item2SalesEstimate = Math.floor((Math.random() * 8) + 1) * 100;
        
        //random number -20 to 20, not including 0
        temp1 = Math.floor((Math.random() * 40) - 20);
        if (temp1 == 0) temp1 = 20; 
        item1Sales = item1SalesEstimate + temp1;
        
        //random number -20 to 20, not including 0
        temp1 = Math.floor((Math.random() * 40) - 20);
        if (temp1 == 0) temp1 = 20; 
        item2Sales = item2SalesEstimate + temp1;
        
        newQuestion.correctAnswer = (item1SalesEstimate * item1CostEstimate) + (item2SalesEstimate * item2CostEstimate);
    
    }while(newQuestion.correctAnswer % 10000 != 0);  //End divisible by 10000 loop
    
    var ia1, ia2, ia3;
    
    //Randomness to to determine incorrect answers.
    //All are 1,000's apart. 4 possible scenarios
    temp1 = Math.floor(Math.random() * 4);
    
    var tempCorrectAnswer = newQuestion.correctAnswer;
    if (temp1 == 0) // correct answer is lowest
    {
        ia1 = tempCorrectAnswer + 10000;
        ia2 = tempCorrectAnswer + 20000;
        ia3 = tempCorrectAnswer + 30000;
    }
    else if (temp1 == 1) // correct answer is second lowest
    {
        ia1 = tempCorrectAnswer - 10000;
        ia2 = tempCorrectAnswer + 10000;
        ia3 = tempCorrectAnswer + 20000;
    }
    else if (temp1 == 2) // correct answer is second highest
    {
        ia1 = tempCorrectAnswer - 20000;
        ia2 = tempCorrectAnswer - 10000;
        ia3 = tempCorrectAnswer + 10000;
    }
    else // correct answer is highest
    {
        ia1 = tempCorrectAnswer - 30000;
        ia2 = tempCorrectAnswer - 20000;
        ia3 = tempCorrectAnswer - 10000;
    }
    
    newQuestion.incorrect1 = ia1;
    newQuestion.incorrect2 = ia2;
    newQuestion.incorrect3 = ia3;
    
    newQuestion.question = "A " + store + " sells " + item1 + " for $" + item1Cost + " and " + item2 + " for $" + item2Cost + ". Last month, they sold " + item1Sales + " " + item1 + " and " + item2Sales + " " + item2 + ". What is the closest estimate for the total amount of many the " + store + " made on these two items last month?";
    
    return newQuestion;
}